print("hello to the world of CICD")
print("helloooooooo")
print("hoooooollllaaaaaa")
print("helloworld")
print("----------//////////////////-----------")
print("Welcome to the world of CICD with Jenkins")