print("hello to the world of CICD")
print("helloooooooo")
print("hoooooollllaaaaaa")
print("helloworld")
print("----------//////////////////-----------")
Print("Welcome to the world of CICD with Jenkins")